- Ajout d'un resource bundle pour l'i18n
DaKarInternational/DaKar pull request #25
Opened 2018-10-27 13:03 UTC by shulolo

- Endpoint et test

2018-10-27 22:32 UTC, blablanumerodeux requested changes

2018-10-27 22:32 UTC, blablanumerodeux commented on src/main/java/com/dakar/dakar/DakarApplication.java
> +     * Permet d'utiliser le resource bundle pour récupérer des messages
```suggestion
     * MessageSource bean definition so that we can fetch the i18n properties 
```

2018-10-27 22:32 UTC, blablanumerodeux commented on src/main/java/com/dakar/dakar/controller/ReactiveController.java
> +                {
please move the { up

2018-10-27 22:32 UTC, blablanumerodeux commented on src/main/java/com/dakar/dakar/controller/ReactiveController.java
> +                    }
```suggestion
                    } else {
```

2018-10-27 22:32 UTC, blablanumerodeux commented on src/main/java/com/dakar/dakar/controller/ReactiveController.java
> +                    else{
```suggestion
                    
```

2018-10-27 22:33 UTC, blablanumerodeux commented
please rename the PR like that : develop <- maFeature : short description

2018-10-27 22:55 UTC, shulolo commented on src/main/java/com/dakar/dakar/controller/ReactiveController.java
> +                {
Ok

2018-10-27 23:32 UTC, blablanumerodeux commented
there are conflicts

2018-10-28 20:21 UTC, blablanumerodeux submitted a review, later dismissed

2018-10-28 20:21 UTC, blablanumerodeux commented on src/main/java/com/dakar/dakar/DakarApplication.java
> +
```suggestion
```

2018-10-28 20:21 UTC, blablanumerodeux commented on src/test/java/com/dakar/dakar/integration/ReactiveControllerTest.java
> +        this.webClient.get().uri("/welcome/en/Damien")
```suggestion
        this.webClient.get()
        .uri("/welcome/en/Damien")
```

2018-10-28 20:40 UTC, blablanumerodeux approved these changes

2018-10-28 20:42 UTC, shulolo commented
endpoint test à reformatter

2018-10-28 21:46 UTC, merged