develop <- features/circleci
DaKarInternational/DaKar pull request #46
Opened 2019-06-23 02:30 UTC by blablanumerodeux

2019-06-29 11:17 UTC, shulolo commented on .circleci/docker-compose-prod.yml
> +    image: "couchbase:5.1.0"
J'ai oublié pourquoi on fixe la version?

2019-06-29 11:17 UTC, shulolo commented on .circleci/deploy.sh
à quoi sert ce fichier déjà ?

2019-06-29 11:19 UTC, shulolo requested changes

2019-06-29 11:19 UTC, shulolo commented on README.MD
> +docker-compose -f docker-compose-prod.yml exec couch bash
il faudrait indiquer peut être à quoi servent les commandes

2019-06-29 17:10 UTC, blablanumerodeux commented on .circleci/docker-compose-prod.yml
> +    image: "couchbase:5.1.0"
En prod on est pas obligé. Mais c'est juste pour être cohérent avec notre base de test. 
Puis sinon faut mettre à jour notre fichier configure-db sinon les tests passent plus.

2019-06-29 17:11 UTC, blablanumerodeux commented on .circleci/deploy.sh
C'est les commandes que circle ci va exécuter automatiquement sur notre vps.

2019-06-29 17:12 UTC, blablanumerodeux commented on README.MD
> +docker-compose -f docker-compose-prod.yml exec couch bash
Oui je vais faire ça

2019-06-30 20:39 UTC, shulolo approved these changes

2019-06-30 20:41 UTC, merged